root = "."
tmp_dir = ".air"

[build]
  cmd = "go build -o ./.air/main ./cmd/main.go"
  bin = ".air/main"
  full_bin = "APP_ENV=dev APP_USER=air ./.air/main"
  include_ext = ["go", "tpl", "tmpl", "html", "css", "js", "env", "yaml"]
  exclude_dir = [".air", "assets", "vendor", "bin", "build", "deploy"]
  include_dir = []
  exclude_regex = ["_test.go"]
  exclude_file = []
  exclude_unchanged = true
  log = "air.log"
  args_bin = []
  stop_on_error = true
  send_interrupt = false
  delay = 1000
  kill_delay = 500

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
