stages:
  - build
  - release

build:
    stage: build
    image: golang:latest
    script:
        - make build-all
    artifacts:
        paths:
        - ./bin
    rules:
        - if: '$CI_COMMIT_TAG'

release:
    stage: release
    image: gitlab/glab:latest
    needs: ["build"]
    before_script:
        - glab auth login --job-token $CI_JOB_TOKEN --hostname $CI_SERVER_HOST --api-protocol $CI_SERVER_PROTOCOL
    script:
        - glab release create $CI_COMMIT_TAG --notes "$CI_COMMIT_TAG"
        - glab release upload $CI_COMMIT_TAG ./bin/*
    rules:
        - if: '$CI_COMMIT_TAG'
